{% set name = "docfx" %}
{% set version = "2.78.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/docfx/archive/v{{ version }}.tar.gz
  sha256: d4b2c80d2042ec81b85b9ae5dd026a6dde71c8029db3113d5a101d07dc078ccb

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - docfx --help

about:
  home: https://github.com/dotnet/docfx
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Static site generator for .NET API documentation.
  dev_url: https://github.com/dotnet/docfx

extra:
  recipe-maintainers:
    - danielnachun
