context:
  version: "2.81.0"

package:
  name: docfx
  version: ${{ version }}

source:
  url: https://github.com/dotnet/docfx/archive/v${{ version }}.tar.gz
  sha256: 55b492cab70a7f883ea5e9a7a134a23d25d70e97153b61d1083ad6b5fa6e2d68

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - docfx --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Static site generator for .NET API documentation.
  homepage: https://github.com/dotnet/docfx
  repository: https://github.com/dotnet/docfx

extra:
  recipe-maintainers:
    - danielnachun
