context:
  version: "2.80.1"

package:
  name: docfx
  version: ${{ version }}

source:
  url: https://github.com/dotnet/docfx/archive/v${{ version }}.tar.gz
  sha256: 89607eba1d832063bccbe1be365d88ddec9ee90f3098e8081f9ba922c6916baf

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - docfx --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Static site generator for .NET API documentation.
  homepage: https://github.com/dotnet/docfx
  repository: https://github.com/dotnet/docfx

extra:
  recipe-maintainers:
    - danielnachun
